project_id = "oqdqcfllhpbnbyeampjc"

[functions.paypal-webhook]
verify_jwt = false

[api]
port = 54321
external_url = "http://127.0.0.1:54321"

[db]
port = 54322

[auth]
site_url = "http://localhost:3000"
